/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prometheus.pkg215;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class forgotPasswordPage extends javax.swing.JFrame {
    
    //creating connection to database
    Connection connection;
    ResultSet rs;
    PreparedStatement pst;

    /**
     * Creates new form forgotPasswordPage
     */
    public forgotPasswordPage() {
        initComponents();
        connection=JavaDbConnect.databaseConnect();
    }
    
    //Search function to show information
    public void Search(){
        String usr_name=username_textfield.getText();
        String sql="select * from accounts where UserName='"+usr_name+"'";
        try{
            pst=connection.prepareStatement(sql);
            rs=pst.executeQuery();
            if (rs.next()){
            email_textfield.setText(rs.getString(4));
            security_question_textfield.setText(rs.getString(7));
            admin_type_textfield.setText(rs.getString(9));
            rs.close();
            pst.close();
        }
        else{
            JOptionPane.showMessageDialog(null,"Incorrect Username");
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
    
    
    //to retrive password
    public void Retrive(){
        String usr_name=username_textfield.getText();
        String seq_answer=answer_textfield.getText();
        String sql="select * from accounts where SecurityQuestionAnswer='"+seq_answer+"'";
        try{
            pst=connection.prepareStatement(sql);
            rs=pst.executeQuery();
            
            if(rs.next()){
            your_password_textfield.setText(rs.getString(5));
            
           }
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        forgot_password_base_panel = new javax.swing.JPanel();
        security_qustion_lable = new javax.swing.JLabel();
        your_password_textfield = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        select_admin_type_label = new javax.swing.JLabel();
        email_textfield = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        your_password_label = new javax.swing.JLabel();
        username_textfield = new javax.swing.JTextField();
        username_label = new javax.swing.JLabel();
        security_question_textfield = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        answer_label = new javax.swing.JLabel();
        admin_type_textfield = new javax.swing.JTextField();
        answer_textfield = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        retrive_button = new javax.swing.JButton();
        email_search_button = new javax.swing.JButton();
        exit_button = new javax.swing.JButton();
        email_label = new javax.swing.JLabel();
        home_button = new javax.swing.JButton();
        forgot_password_page_background_image_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(960, 540));

        forgot_password_base_panel.setPreferredSize(new java.awt.Dimension(960, 540));
        forgot_password_base_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        security_qustion_lable.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        security_qustion_lable.setForeground(new java.awt.Color(255, 255, 255));
        security_qustion_lable.setText("Your Security Question");
        forgot_password_base_panel.add(security_qustion_lable, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 220, 40));

        your_password_textfield.setEditable(false);
        your_password_textfield.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        your_password_textfield.setForeground(new java.awt.Color(255, 0, 0));
        your_password_textfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        your_password_textfield.setBorder(null);
        your_password_textfield.setOpaque(false);
        forgot_password_base_panel.add(your_password_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 330, 40));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        forgot_password_base_panel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 330, 20));

        select_admin_type_label.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        select_admin_type_label.setForeground(new java.awt.Color(255, 255, 255));
        select_admin_type_label.setText("Admin Type");
        forgot_password_base_panel.add(select_admin_type_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 120, 40));

        email_textfield.setEditable(false);
        email_textfield.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        email_textfield.setForeground(new java.awt.Color(51, 51, 51));
        email_textfield.setBorder(null);
        email_textfield.setOpaque(false);
        email_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_textfieldActionPerformed(evt);
            }
        });
        forgot_password_base_panel.add(email_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 330, 40));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        forgot_password_base_panel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 330, 10));

        your_password_label.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        your_password_label.setForeground(new java.awt.Color(255, 255, 255));
        your_password_label.setText("Your Password");
        forgot_password_base_panel.add(your_password_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 150, 40));

        username_textfield.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        username_textfield.setForeground(new java.awt.Color(51, 51, 51));
        username_textfield.setText("Enter Username");
        username_textfield.setBorder(null);
        username_textfield.setOpaque(false);
        forgot_password_base_panel.add(username_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 330, 40));

        username_label.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        username_label.setForeground(new java.awt.Color(255, 255, 255));
        username_label.setText("Username");
        forgot_password_base_panel.add(username_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 150, 40));

        security_question_textfield.setEditable(false);
        security_question_textfield.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        security_question_textfield.setForeground(new java.awt.Color(51, 51, 51));
        security_question_textfield.setBorder(null);
        security_question_textfield.setOpaque(false);
        security_question_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                security_question_textfieldActionPerformed(evt);
            }
        });
        forgot_password_base_panel.add(security_question_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 330, 40));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        forgot_password_base_panel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 330, 20));

        answer_label.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        answer_label.setForeground(new java.awt.Color(255, 255, 255));
        answer_label.setText("Answer");
        forgot_password_base_panel.add(answer_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 150, 40));

        admin_type_textfield.setEditable(false);
        admin_type_textfield.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        admin_type_textfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        admin_type_textfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        admin_type_textfield.setOpaque(false);
        admin_type_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_type_textfieldActionPerformed(evt);
            }
        });
        forgot_password_base_panel.add(admin_type_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 160, 50));

        answer_textfield.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        answer_textfield.setForeground(new java.awt.Color(51, 51, 51));
        answer_textfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        answer_textfield.setText("Submit your Answer");
        answer_textfield.setBorder(null);
        answer_textfield.setOpaque(false);
        forgot_password_base_panel.add(answer_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 330, 40));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        forgot_password_base_panel.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 330, 10));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        forgot_password_base_panel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 330, 20));

        retrive_button.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        retrive_button.setForeground(new java.awt.Color(255, 255, 255));
        retrive_button.setText("Retrive");
        retrive_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrive_buttonActionPerformed(evt);
            }
        });
        forgot_password_base_panel.add(retrive_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 90, 40));

        email_search_button.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        email_search_button.setForeground(new java.awt.Color(255, 255, 255));
        email_search_button.setText("Search");
        email_search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_search_buttonActionPerformed(evt);
            }
        });
        forgot_password_base_panel.add(email_search_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 90, 40));

        exit_button.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        exit_button.setForeground(new java.awt.Color(255, 255, 255));
        exit_button.setText("Exit");
        forgot_password_base_panel.add(exit_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 30));

        email_label.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        email_label.setForeground(new java.awt.Color(255, 255, 255));
        email_label.setText("Email");
        forgot_password_base_panel.add(email_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 150, 40));

        home_button.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        home_button.setForeground(new java.awt.Color(255, 255, 255));
        home_button.setText("Home");
        home_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_buttonActionPerformed(evt);
            }
        });
        forgot_password_base_panel.add(home_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        forgot_password_page_background_image_label.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Desktop\\java home examples\\Prometheus-215\\images\\prometheus_backgrounds\\forgot_password_page_background.jpg")); // NOI18N
        forgot_password_base_panel.add(forgot_password_page_background_image_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(forgot_password_base_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(forgot_password_base_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(976, 579));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void email_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_textfieldActionPerformed

    private void security_question_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_security_question_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_security_question_textfieldActionPerformed

    private void email_search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_search_buttonActionPerformed
        // TODO add your handling code here:
        Search();
    }//GEN-LAST:event_email_search_buttonActionPerformed

    private void retrive_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrive_buttonActionPerformed
        // TODO add your handling code here:
        Retrive();
    }//GEN-LAST:event_retrive_buttonActionPerformed

    private void admin_type_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_type_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admin_type_textfieldActionPerformed

    private void home_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_buttonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        HomePage hp=new HomePage();
        hp.setVisible(true);
    }//GEN-LAST:event_home_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgotPasswordPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgotPasswordPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgotPasswordPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgotPasswordPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgotPasswordPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField admin_type_textfield;
    private javax.swing.JLabel answer_label;
    private javax.swing.JTextField answer_textfield;
    private javax.swing.JLabel email_label;
    private javax.swing.JButton email_search_button;
    private javax.swing.JTextField email_textfield;
    private javax.swing.JButton exit_button;
    private javax.swing.JPanel forgot_password_base_panel;
    private javax.swing.JLabel forgot_password_page_background_image_label;
    private javax.swing.JButton home_button;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton retrive_button;
    private javax.swing.JTextField security_question_textfield;
    private javax.swing.JLabel security_qustion_lable;
    private javax.swing.JLabel select_admin_type_label;
    private javax.swing.JLabel username_label;
    private javax.swing.JTextField username_textfield;
    private javax.swing.JLabel your_password_label;
    private javax.swing.JTextField your_password_textfield;
    // End of variables declaration//GEN-END:variables
}
