/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prometheus.pkg215;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Acer
 */
public class TrafficPolicePage extends javax.swing.JFrame {

    //creating connection to database
    Connection connection;
    ResultSet rs;
    PreparedStatement pst;

    /**
     * Creates new form TrafficPolicePage
     */
    public TrafficPolicePage() {
        initComponents();

        connection = JavaDbConnect.databaseConnect();
        DriverInfoUpdateTable();
        DriverShortInfoTable();
        dateAndTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolber = new javax.swing.JToolBar();
        home_toolber_button = new javax.swing.JButton();
        signout_toobar_button = new javax.swing.JButton();
        panel_for_tabpane = new javax.swing.JPanel();
        tabpane = new javax.swing.JTabbedPane();
        datatable_tabpane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        driverinfo_table = new javax.swing.JTable();
        report_tabpane = new javax.swing.JPanel();
        statistics_tabpane = new javax.swing.JPanel();
        docuuments_tabpane = new javax.swing.JPanel();
        email_tabpane = new javax.swing.JPanel();
        action_panel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        clear_button = new javax.swing.JButton();
        delete_button = new javax.swing.JButton();
        add_button = new javax.swing.JButton();
        edit_button = new javax.swing.JButton();
        search_textfield = new javax.swing.JTextField();
        search_button = new javax.swing.JButton();
        drivers_info_panel = new javax.swing.JPanel();
        drivers_id_label = new javax.swing.JLabel();
        drivers_id_textfield = new javax.swing.JTextField();
        firstName_label = new javax.swing.JLabel();
        firstName_textfield = new javax.swing.JTextField();
        lastName_label = new javax.swing.JLabel();
        lastName_textfield = new javax.swing.JTextField();
        fullName_label = new javax.swing.JLabel();
        fullName_textfield = new javax.swing.JTextField();
        dob_label = new javax.swing.JLabel();
        dob_textfield = new javax.swing.JTextField();
        gender_label = new javax.swing.JLabel();
        gender_combobox = new javax.swing.JComboBox<>();
        bloodGroup_label = new javax.swing.JLabel();
        religion_label = new javax.swing.JLabel();
        religion_textfield = new javax.swing.JTextField();
        emailAddress_label = new javax.swing.JLabel();
        emailAddress_textfield = new javax.swing.JTextField();
        city_label = new javax.swing.JLabel();
        city_textfield = new javax.swing.JTextField();
        address_label = new javax.swing.JLabel();
        address_textfield = new javax.swing.JTextField();
        drivingLicenseNo_label = new javax.swing.JLabel();
        drivingLicenseNo_textfield = new javax.swing.JTextField();
        licenseType_label = new javax.swing.JLabel();
        licenseType_combobox = new javax.swing.JComboBox<>();
        issuedDate_label = new javax.swing.JLabel();
        issuedDate_textfield = new javax.swing.JTextField();
        expiredDate_textfield = new javax.swing.JTextField();
        expiredDate_label = new javax.swing.JLabel();
        points_label = new javax.swing.JLabel();
        points_textfield = new javax.swing.JTextField();
        bloodGroup_textfield = new javax.swing.JTextField();
        image_panel = new javax.swing.JPanel();
        data_panel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        drivershortinfo_table = new javax.swing.JTable();
        menubar = new javax.swing.JMenuBar();
        file_menu = new javax.swing.JMenu();
        close_menuitem = new javax.swing.JMenuItem();
        exit_menuitem = new javax.swing.JMenuItem();
        help_menu = new javax.swing.JMenu();
        offline_help_menu_item = new javax.swing.JMenuItem();
        date_menu = new javax.swing.JMenu();
        time_menu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1365, 730));
        setResizable(false);
        setSize(new java.awt.Dimension(1365, 730));

        toolber.setRollover(true);

        home_toolber_button.setText("Home");
        home_toolber_button.setFocusable(false);
        home_toolber_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        home_toolber_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        home_toolber_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_toolber_buttonActionPerformed(evt);
            }
        });
        toolber.add(home_toolber_button);

        signout_toobar_button.setText("Sign Out");
        signout_toobar_button.setFocusable(false);
        signout_toobar_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        signout_toobar_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolber.add(signout_toobar_button);

        panel_for_tabpane.setBackground(new java.awt.Color(0, 153, 153));

        tabpane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Action Panel", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB Demi", 1, 10))); // NOI18N
        tabpane.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N

        driverinfo_table.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        driverinfo_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        driverinfo_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                driverinfo_tableMouseClicked(evt);
            }
        });
        driverinfo_table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                driverinfo_tableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(driverinfo_table);

        javax.swing.GroupLayout datatable_tabpaneLayout = new javax.swing.GroupLayout(datatable_tabpane);
        datatable_tabpane.setLayout(datatable_tabpaneLayout);
        datatable_tabpaneLayout.setHorizontalGroup(
            datatable_tabpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datatable_tabpaneLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 915, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 773, Short.MAX_VALUE))
        );
        datatable_tabpaneLayout.setVerticalGroup(
            datatable_tabpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datatable_tabpaneLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 127, Short.MAX_VALUE))
        );

        tabpane.addTab("Data Table", datatable_tabpane);

        javax.swing.GroupLayout report_tabpaneLayout = new javax.swing.GroupLayout(report_tabpane);
        report_tabpane.setLayout(report_tabpaneLayout);
        report_tabpaneLayout.setHorizontalGroup(
            report_tabpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1688, Short.MAX_VALUE)
        );
        report_tabpaneLayout.setVerticalGroup(
            report_tabpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );

        tabpane.addTab("Report", report_tabpane);

        javax.swing.GroupLayout statistics_tabpaneLayout = new javax.swing.GroupLayout(statistics_tabpane);
        statistics_tabpane.setLayout(statistics_tabpaneLayout);
        statistics_tabpaneLayout.setHorizontalGroup(
            statistics_tabpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1688, Short.MAX_VALUE)
        );
        statistics_tabpaneLayout.setVerticalGroup(
            statistics_tabpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );

        tabpane.addTab("Statistics", statistics_tabpane);

        javax.swing.GroupLayout docuuments_tabpaneLayout = new javax.swing.GroupLayout(docuuments_tabpane);
        docuuments_tabpane.setLayout(docuuments_tabpaneLayout);
        docuuments_tabpaneLayout.setHorizontalGroup(
            docuuments_tabpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1688, Short.MAX_VALUE)
        );
        docuuments_tabpaneLayout.setVerticalGroup(
            docuuments_tabpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );

        tabpane.addTab("Documents", docuuments_tabpane);

        javax.swing.GroupLayout email_tabpaneLayout = new javax.swing.GroupLayout(email_tabpane);
        email_tabpane.setLayout(email_tabpaneLayout);
        email_tabpaneLayout.setHorizontalGroup(
            email_tabpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1688, Short.MAX_VALUE)
        );
        email_tabpaneLayout.setVerticalGroup(
            email_tabpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );

        tabpane.addTab("Email", email_tabpane);

        javax.swing.GroupLayout panel_for_tabpaneLayout = new javax.swing.GroupLayout(panel_for_tabpane);
        panel_for_tabpane.setLayout(panel_for_tabpaneLayout);
        panel_for_tabpaneLayout.setHorizontalGroup(
            panel_for_tabpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabpane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        panel_for_tabpaneLayout.setVerticalGroup(
            panel_for_tabpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_for_tabpaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tabpane, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        action_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Commands", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 12), new java.awt.Color(0, 102, 153))); // NOI18N

        clear_button.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        clear_button.setText("Clear");
        clear_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_buttonActionPerformed(evt);
            }
        });

        delete_button.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        delete_button.setText("Delete");

        add_button.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        add_button.setText("Add");
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });

        edit_button.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        edit_button.setText("Edit");
        edit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clear_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delete_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(add_button, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(edit_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(clear_button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        search_textfield.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        search_textfield.setText("Search");
        search_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_textfieldKeyReleased(evt);
            }
        });

        search_button.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Desktop\\java home examples\\Prometheus-215\\images\\prometheus_icons\\search_icon.png")); // NOI18N

        javax.swing.GroupLayout action_panelLayout = new javax.swing.GroupLayout(action_panel);
        action_panel.setLayout(action_panelLayout);
        action_panelLayout.setHorizontalGroup(
            action_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(action_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(action_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(search_textfield))
                .addContainerGap())
            .addGroup(action_panelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        action_panelLayout.setVerticalGroup(
            action_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, action_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(search_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        drivers_info_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Driver's Info", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB Demi", 1, 11))); // NOI18N

        drivers_id_label.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        drivers_id_label.setText("Driver's Id");

        firstName_label.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        firstName_label.setText("First Name");

        lastName_label.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        lastName_label.setText("Last Name");

        fullName_label.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        fullName_label.setText("Full Name");

        dob_label.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        dob_label.setText("Dathe of Birth");

        gender_label.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        gender_label.setText("Gender");

        gender_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        bloodGroup_label.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        bloodGroup_label.setText("Blood Group");

        religion_label.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        religion_label.setText("Religion");

        emailAddress_label.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        emailAddress_label.setText("Email Address");

        city_label.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        city_label.setText("City");

        address_label.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        address_label.setText("Address");

        drivingLicenseNo_label.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        drivingLicenseNo_label.setText("Driving License No");

        licenseType_label.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        licenseType_label.setText("License Type");

        licenseType_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Professional", "Non-Professional" }));

        issuedDate_label.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        issuedDate_label.setText("Issued Date");

        expiredDate_label.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        expiredDate_label.setText("Expired Date");

        points_label.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        points_label.setText("Points");

        javax.swing.GroupLayout drivers_info_panelLayout = new javax.swing.GroupLayout(drivers_info_panel);
        drivers_info_panel.setLayout(drivers_info_panelLayout);
        drivers_info_panelLayout.setHorizontalGroup(
            drivers_info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drivers_info_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(drivers_info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(drivers_info_panelLayout.createSequentialGroup()
                        .addComponent(bloodGroup_label, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bloodGroup_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(drivers_info_panelLayout.createSequentialGroup()
                        .addComponent(drivers_id_label, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(drivers_id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(drivers_info_panelLayout.createSequentialGroup()
                        .addComponent(firstName_label, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(firstName_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(drivers_info_panelLayout.createSequentialGroup()
                        .addComponent(lastName_label, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastName_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(drivers_info_panelLayout.createSequentialGroup()
                        .addComponent(fullName_label, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fullName_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(drivers_info_panelLayout.createSequentialGroup()
                        .addComponent(dob_label, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dob_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(drivers_info_panelLayout.createSequentialGroup()
                        .addComponent(gender_label, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gender_combobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(drivers_info_panelLayout.createSequentialGroup()
                        .addComponent(religion_label, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(religion_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(drivers_info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(drivers_info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, drivers_info_panelLayout.createSequentialGroup()
                            .addComponent(licenseType_label, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(licenseType_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(drivers_info_panelLayout.createSequentialGroup()
                            .addComponent(emailAddress_label, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(emailAddress_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(drivers_info_panelLayout.createSequentialGroup()
                            .addComponent(city_label, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(city_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(drivers_info_panelLayout.createSequentialGroup()
                            .addComponent(address_label, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(address_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(drivers_info_panelLayout.createSequentialGroup()
                            .addComponent(drivingLicenseNo_label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(drivingLicenseNo_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(drivers_info_panelLayout.createSequentialGroup()
                        .addComponent(issuedDate_label, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(issuedDate_textfield))
                    .addGroup(drivers_info_panelLayout.createSequentialGroup()
                        .addComponent(expiredDate_label, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(expiredDate_textfield))
                    .addGroup(drivers_info_panelLayout.createSequentialGroup()
                        .addComponent(points_label, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(points_textfield)))
                .addGap(28, 28, 28))
        );
        drivers_info_panelLayout.setVerticalGroup(
            drivers_info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drivers_info_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(drivers_info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drivers_id_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drivers_id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailAddress_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailAddress_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(drivers_info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstName_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstName_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(city_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(city_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(drivers_info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastName_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastName_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(drivers_info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullName_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullName_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drivingLicenseNo_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drivingLicenseNo_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(drivers_info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dob_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dob_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(licenseType_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(licenseType_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(drivers_info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gender_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gender_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issuedDate_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issuedDate_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(drivers_info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(drivers_info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bloodGroup_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(expiredDate_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(expiredDate_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bloodGroup_textfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(drivers_info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(religion_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(religion_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(points_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(points_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        image_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout image_panelLayout = new javax.swing.GroupLayout(image_panel);
        image_panel.setLayout(image_panelLayout);
        image_panelLayout.setHorizontalGroup(
            image_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );
        image_panelLayout.setVerticalGroup(
            image_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        data_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        drivershortinfo_table.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        drivershortinfo_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        drivershortinfo_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                drivershortinfo_tableMouseClicked(evt);
            }
        });
        drivershortinfo_table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                drivershortinfo_tableKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(drivershortinfo_table);

        javax.swing.GroupLayout data_panelLayout = new javax.swing.GroupLayout(data_panel);
        data_panel.setLayout(data_panelLayout);
        data_panelLayout.setHorizontalGroup(
            data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, data_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        data_panelLayout.setVerticalGroup(
            data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, data_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        file_menu.setText("File");

        close_menuitem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        close_menuitem.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Desktop\\java home examples\\Prometheus-215\\images\\prometheus_icons\\close_icon.png")); // NOI18N
        close_menuitem.setText("Close");
        close_menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_menuitemActionPerformed(evt);
            }
        });
        file_menu.add(close_menuitem);

        exit_menuitem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        exit_menuitem.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Desktop\\java home examples\\Prometheus-215\\images\\prometheus_icons\\exit_icon.png")); // NOI18N
        exit_menuitem.setText("Exit");
        exit_menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_menuitemActionPerformed(evt);
            }
        });
        file_menu.add(exit_menuitem);

        menubar.add(file_menu);

        help_menu.setText("Help");

        offline_help_menu_item.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        offline_help_menu_item.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Desktop\\java home examples\\Prometheus-215\\images\\prometheus_icons\\help_icon.png")); // NOI18N
        offline_help_menu_item.setText("Offline Help");
        offline_help_menu_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offline_help_menu_itemActionPerformed(evt);
            }
        });
        help_menu.add(offline_help_menu_item);

        menubar.add(help_menu);

        date_menu.setText("Date");
        menubar.add(date_menu);

        time_menu.setText("Time");
        menubar.add(time_menu);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(action_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(drivers_info_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(image_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(data_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panel_for_tabpane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolber, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(drivers_info_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(image_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(data_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(action_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_for_tabpane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DriverInfoUpdateTable() {
        try {
            String sql = "select id,Full_name,Gender,Blood_Group,Email,City,Issued,Expired,License_Type from DriverInfo";
            pst = connection.prepareStatement(sql);
            rs = pst.executeQuery();
            driverinfo_table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }

    }

    private void DriverShortInfoTable() {
        try {
            String sql = "select id,License_Type,Points from DriverInfo";
            pst = connection.prepareStatement(sql);
            rs = pst.executeQuery();
            drivershortinfo_table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }

    }

    private void dateAndTime() {
        //static date and time
        Calendar cal = new GregorianCalendar();
        int day = cal.get(Calendar.DAY_OF_MONTH);
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        date_menu.setText("Date: " + day + "/" + (month + 1) + "/" + year);
        date_menu.setForeground(Color.BLUE);

        int second = cal.get(Calendar.SECOND);
        int minute = cal.get(Calendar.MINUTE);
        int hour = cal.get(Calendar.HOUR);
        time_menu.setText("Login Time: " + hour + ":" + minute + ":" + second);
        time_menu.setForeground(Color.RED);

    }

    private void close_menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_menuitemActionPerformed
        // TODO add your handling code here:
        try {
            setVisible(false);
            LoginPage lp = new LoginPage();
            lp.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                rs.close();
                pst.close();
                connection.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

    }//GEN-LAST:event_close_menuitemActionPerformed

    private void exit_menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_menuitemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit_menuitemActionPerformed

    private void home_toolber_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_toolber_buttonActionPerformed
        // TODO add your handling code here:

        try {
            setVisible(false);
            HomePage hp = new HomePage();
            hp.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                rs.close();
                pst.close();
                connection.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

    }//GEN-LAST:event_home_toolber_buttonActionPerformed

    private void getValues() {
        try {

            drivers_id_textfield.setText(rs.getString("Id"));
            firstName_textfield.setText(rs.getString("First_Name"));
            lastName_textfield.setText(rs.getString("Last_Name"));
            fullName_textfield.setText(rs.getString("Full_Name"));
            dob_textfield.setText(rs.getString("Dob"));
            gender_combobox.setSelectedItem(rs.getString("Gender"));
            bloodGroup_textfield.setText(rs.getString("Blood_Group"));
            religion_textfield.setText(rs.getString("Religion"));
            emailAddress_textfield.setText(rs.getString("Email"));
            city_textfield.setText(rs.getString("City"));
            address_textfield.setText(rs.getString("Address"));
            drivingLicenseNo_textfield.setText(rs.getString("Driving_License_No"));
            licenseType_combobox.setSelectedItem(rs.getString("License_Type"));
            issuedDate_textfield.setText(rs.getString("Issued"));
            expiredDate_textfield.setText(rs.getString("Expired"));
            points_textfield.setText(rs.getString("Points"));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void drivershortinfo_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drivershortinfo_tableMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            int row = drivershortinfo_table.getSelectedRow();
            String tableClick = (drivershortinfo_table.getModel().getValueAt(row, 0).toString());
            String sql = "select * from DriverInfo where Id='" + tableClick + "' ";
            pst = connection.prepareStatement(sql);
            rs = pst.executeQuery();

            if (rs.next()) {
                getValues();

            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_drivershortinfo_tableMouseClicked

    private void drivershortinfo_tableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_drivershortinfo_tableKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            try {
                // TODO add your handling code here:
                int row = drivershortinfo_table.getSelectedRow();
                String tableClick = (drivershortinfo_table.getModel().getValueAt(row, 0).toString());
                String sql = "select * from DriverInfo where Id='" + tableClick + "' ";
                pst = connection.prepareStatement(sql);
                rs = pst.executeQuery();

                if (rs.next()) {
                    getValues();
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_drivershortinfo_tableKeyReleased

    private void driverinfo_tableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_driverinfo_tableKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            try {
                // TODO add your handling code here:
                int row = driverinfo_table.getSelectedRow();
                String tableClick = (driverinfo_table.getModel().getValueAt(row, 0).toString());
                String sql = "select * from DriverInfo where Id='" + tableClick + "' ";
                pst = connection.prepareStatement(sql);
                rs = pst.executeQuery();

                if (rs.next()) {
                    getValues();
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_driverinfo_tableKeyReleased

    private void driverinfo_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_driverinfo_tableMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            int row = driverinfo_table.getSelectedRow();
            String tableClick = (driverinfo_table.getModel().getValueAt(row, 0).toString());
            String sql = "select * from DriverInfo where Id='" + tableClick + "' ";
            pst = connection.prepareStatement(sql);
            rs = pst.executeQuery();

            if (rs.next()) {
                getValues();
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_driverinfo_tableMouseClicked

    private void offline_help_menu_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offline_help_menu_itemActionPerformed
        // TODO add your handling code here:
        try {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "Files\\HELP.pdf");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_offline_help_menu_itemActionPerformed

    private void search_textfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_textfieldKeyReleased
        // TODO add your handling code here:
        String sql = "select * from DriverInfo where Full_Name=?";
        try {
            pst = connection.prepareStatement(sql);
            pst.setString(1, search_textfield.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                getValues();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        String sql1 = "select * from DriverInfo where Id=?";
        try {
            pst = connection.prepareStatement(sql1);
            pst.setString(1, search_textfield.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                getValues();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_search_textfieldKeyReleased

    private void clear_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_buttonActionPerformed
        // TODO add your handling code here:
        drivers_id_textfield.setText(null);
        firstName_textfield.setText(null);
        lastName_textfield.setText(null);
        fullName_textfield.setText(null);
        dob_textfield.setText(null);
        gender_combobox.setSelectedItem("Male");
        bloodGroup_textfield.setText(null);
        religion_textfield.setText(null);
        emailAddress_textfield.setText(null);
        city_textfield.setText(null);
        address_textfield.setText(null);
        drivingLicenseNo_textfield.setText(null);
        licenseType_combobox.setSelectedItem("Professional");
        issuedDate_textfield.setText(null);
        expiredDate_textfield.setText(null);
        points_textfield.setText(null);

    }//GEN-LAST:event_clear_buttonActionPerformed

    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        // TODO add your handling code here:
        String sql="insert into DriverInfo(Id,First_Name,Last_Name,Full_Name,Dob,Gender,Blood_Group,"
                + "Religion,Email,City,Address,Driving_License_No,License_Type,Issued,Expired,Points)"
                + " values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        try{
            pst=connection.prepareStatement(sql);
            pst.setString(1,drivers_id_textfield.getText());
            pst.setString(2,firstName_textfield.getText());
            pst.setString(3,lastName_textfield.getText());
            pst.setString(4,fullName_textfield.getText());
            pst.setString(5,dob_textfield.getText());
            pst.setString(6,(String)gender_combobox.getSelectedItem());
            pst.setString(7,bloodGroup_textfield.getText());
            pst.setString(8,religion_textfield.getText());
            pst.setString(9,emailAddress_textfield.getText());
            pst.setString(10,city_textfield.getText());
            pst.setString(11,address_textfield.getText());
            pst.setString(12,drivingLicenseNo_textfield.getText());
            pst.setString(13,(String)licenseType_combobox.getSelectedItem());
            pst.setString(14,issuedDate_textfield.getText());
            pst.setString(15,expiredDate_textfield.getText());
            pst.setString(16,points_textfield.getText());
            
            pst.execute();
            
            JOptionPane.showMessageDialog(rootPane,"Info Saved");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        //calling two Tables manually after insertion to emidiate show
        DriverInfoUpdateTable();
        DriverShortInfoTable();
        
    }//GEN-LAST:event_add_buttonActionPerformed

    private void edit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_buttonActionPerformed
        // TODO add your handling code here:
        String sql="update DriverInfo set First_Name=?,Last_Name=?,Full_Name=?,Dob=?,Gender=?,Blood_Group=?,Religion=?,Email=?,City=?,Address=?,Driving_License_No=?,License_Type=?,Issued=?,Expired=?,Points=? where Id=?";
        try{
            pst=connection.prepareStatement(sql);
            
            pst.setString(1,firstName_textfield.getText());
            pst.setString(2,lastName_textfield.getText());
            pst.setString(3,fullName_textfield.getText());
            pst.setString(4,dob_textfield.getText());
            pst.setString(5,(String)gender_combobox.getSelectedItem());
            pst.setString(6,bloodGroup_textfield.getText());
            pst.setString(7,religion_textfield.getText());
            pst.setString(8,emailAddress_textfield.getText());
            pst.setString(9,city_textfield.getText());
            pst.setString(10,address_textfield.getText());
            pst.setString(11,drivingLicenseNo_textfield.getText());
            pst.setString(12,(String)licenseType_combobox.getSelectedItem());
            pst.setString(13,issuedDate_textfield.getText());
            pst.setString(14,expiredDate_textfield.getText());
            pst.setString(15,points_textfield.getText());
            
             pst.setString(16,drivers_id_textfield.getText());
            
            pst.execute();
            
            JOptionPane.showMessageDialog(rootPane,"Info Updated");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        //calling two Tables manually after insertion to emidiate show
        DriverInfoUpdateTable();
        DriverShortInfoTable();
    }//GEN-LAST:event_edit_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrafficPolicePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrafficPolicePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrafficPolicePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrafficPolicePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrafficPolicePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel action_panel;
    private javax.swing.JButton add_button;
    private javax.swing.JLabel address_label;
    private javax.swing.JTextField address_textfield;
    private javax.swing.JLabel bloodGroup_label;
    private javax.swing.JTextField bloodGroup_textfield;
    private javax.swing.JLabel city_label;
    private javax.swing.JTextField city_textfield;
    private javax.swing.JButton clear_button;
    private javax.swing.JMenuItem close_menuitem;
    private javax.swing.JPanel data_panel;
    private javax.swing.JPanel datatable_tabpane;
    private javax.swing.JMenu date_menu;
    private javax.swing.JButton delete_button;
    private javax.swing.JLabel dob_label;
    private javax.swing.JTextField dob_textfield;
    private javax.swing.JPanel docuuments_tabpane;
    private javax.swing.JTable driverinfo_table;
    private javax.swing.JLabel drivers_id_label;
    private javax.swing.JTextField drivers_id_textfield;
    private javax.swing.JPanel drivers_info_panel;
    private javax.swing.JTable drivershortinfo_table;
    private javax.swing.JLabel drivingLicenseNo_label;
    private javax.swing.JTextField drivingLicenseNo_textfield;
    private javax.swing.JButton edit_button;
    private javax.swing.JLabel emailAddress_label;
    private javax.swing.JTextField emailAddress_textfield;
    private javax.swing.JPanel email_tabpane;
    private javax.swing.JMenuItem exit_menuitem;
    private javax.swing.JLabel expiredDate_label;
    private javax.swing.JTextField expiredDate_textfield;
    private javax.swing.JMenu file_menu;
    private javax.swing.JLabel firstName_label;
    private javax.swing.JTextField firstName_textfield;
    private javax.swing.JLabel fullName_label;
    private javax.swing.JTextField fullName_textfield;
    private javax.swing.JComboBox<String> gender_combobox;
    private javax.swing.JLabel gender_label;
    private javax.swing.JMenu help_menu;
    private javax.swing.JButton home_toolber_button;
    private javax.swing.JPanel image_panel;
    private javax.swing.JLabel issuedDate_label;
    private javax.swing.JTextField issuedDate_textfield;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lastName_label;
    private javax.swing.JTextField lastName_textfield;
    private javax.swing.JComboBox<String> licenseType_combobox;
    private javax.swing.JLabel licenseType_label;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JMenuItem offline_help_menu_item;
    private javax.swing.JPanel panel_for_tabpane;
    private javax.swing.JLabel points_label;
    private javax.swing.JTextField points_textfield;
    private javax.swing.JLabel religion_label;
    private javax.swing.JTextField religion_textfield;
    private javax.swing.JPanel report_tabpane;
    private javax.swing.JButton search_button;
    private javax.swing.JTextField search_textfield;
    private javax.swing.JButton signout_toobar_button;
    private javax.swing.JPanel statistics_tabpane;
    private javax.swing.JTabbedPane tabpane;
    private javax.swing.JMenu time_menu;
    private javax.swing.JToolBar toolber;
    // End of variables declaration//GEN-END:variables
}
