/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prometheus.pkg215;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Acer
 */
public class TrafficPolicePage extends javax.swing.JFrame {

    //creating connection to database
    Connection connection;
    ResultSet rs;
    PreparedStatement pst;

    /**
     * Creates new form TrafficPolicePage
     */
    public TrafficPolicePage() {
        initComponents();

        connection = JavaDbConnect.databaseConnect();
        DriverInfoUpdateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolber = new javax.swing.JToolBar();
        home_toolber_button = new javax.swing.JButton();
        signout_toobar_button = new javax.swing.JButton();
        panel_for_tabpane = new javax.swing.JPanel();
        tabpane = new javax.swing.JTabbedPane();
        datatable_tabpane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        driverinfo_table = new javax.swing.JTable();
        report_tabpane = new javax.swing.JPanel();
        statistics_tabpane = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        Date = new javax.swing.JMenuBar();
        file_menu = new javax.swing.JMenu();
        close_menuitem = new javax.swing.JMenuItem();
        exit_menuitem = new javax.swing.JMenuItem();
        help_menu = new javax.swing.JMenu();
        about_menu = new javax.swing.JMenu();
        Time_menu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1365, 730));
        setResizable(false);
        setSize(new java.awt.Dimension(1365, 730));

        toolber.setRollover(true);

        home_toolber_button.setText("Home");
        home_toolber_button.setFocusable(false);
        home_toolber_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        home_toolber_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        home_toolber_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_toolber_buttonActionPerformed(evt);
            }
        });
        toolber.add(home_toolber_button);

        signout_toobar_button.setText("Sign Out");
        signout_toobar_button.setFocusable(false);
        signout_toobar_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        signout_toobar_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolber.add(signout_toobar_button);

        panel_for_tabpane.setBackground(new java.awt.Color(0, 153, 153));

        tabpane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Action Panel", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB Demi", 1, 10))); // NOI18N
        tabpane.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N

        driverinfo_table.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        driverinfo_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(driverinfo_table);

        javax.swing.GroupLayout datatable_tabpaneLayout = new javax.swing.GroupLayout(datatable_tabpane);
        datatable_tabpane.setLayout(datatable_tabpaneLayout);
        datatable_tabpaneLayout.setHorizontalGroup(
            datatable_tabpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datatable_tabpaneLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 915, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1435, Short.MAX_VALUE))
        );
        datatable_tabpaneLayout.setVerticalGroup(
            datatable_tabpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datatable_tabpaneLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 127, Short.MAX_VALUE))
        );

        tabpane.addTab("Data Table", datatable_tabpane);

        javax.swing.GroupLayout report_tabpaneLayout = new javax.swing.GroupLayout(report_tabpane);
        report_tabpane.setLayout(report_tabpaneLayout);
        report_tabpaneLayout.setHorizontalGroup(
            report_tabpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2350, Short.MAX_VALUE)
        );
        report_tabpaneLayout.setVerticalGroup(
            report_tabpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );

        tabpane.addTab("Report", report_tabpane);

        javax.swing.GroupLayout statistics_tabpaneLayout = new javax.swing.GroupLayout(statistics_tabpane);
        statistics_tabpane.setLayout(statistics_tabpaneLayout);
        statistics_tabpaneLayout.setHorizontalGroup(
            statistics_tabpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2350, Short.MAX_VALUE)
        );
        statistics_tabpaneLayout.setVerticalGroup(
            statistics_tabpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );

        tabpane.addTab("Statistics", statistics_tabpane);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2350, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );

        tabpane.addTab("Documents", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2350, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );

        tabpane.addTab("Email", jPanel6);

        javax.swing.GroupLayout panel_for_tabpaneLayout = new javax.swing.GroupLayout(panel_for_tabpane);
        panel_for_tabpane.setLayout(panel_for_tabpaneLayout);
        panel_for_tabpaneLayout.setHorizontalGroup(
            panel_for_tabpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabpane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        panel_for_tabpaneLayout.setVerticalGroup(
            panel_for_tabpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_for_tabpaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tabpane, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        file_menu.setText("File");

        close_menuitem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        close_menuitem.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Desktop\\java home examples\\Prometheus-215\\images\\prometheus_buttons\\close_icon.png")); // NOI18N
        close_menuitem.setText("Close");
        close_menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_menuitemActionPerformed(evt);
            }
        });
        file_menu.add(close_menuitem);

        exit_menuitem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        exit_menuitem.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Desktop\\java home examples\\Prometheus-215\\images\\prometheus_buttons\\exit_icon.png")); // NOI18N
        exit_menuitem.setText("Exit");
        exit_menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_menuitemActionPerformed(evt);
            }
        });
        file_menu.add(exit_menuitem);

        Date.add(file_menu);

        help_menu.setText("Help");
        Date.add(help_menu);

        about_menu.setText("About");
        Date.add(about_menu);

        Time_menu.setText("Time");
        Date.add(Time_menu);

        setJMenuBar(Date);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolber, javax.swing.GroupLayout.PREFERRED_SIZE, 1022, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_for_tabpane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolber, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 379, Short.MAX_VALUE)
                .addComponent(panel_for_tabpane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DriverInfoUpdateTable(){
        try {
            String sql= "select id,Full_name,Gender,Blood_Group,Email,City,Issued,Expired,License_Type from DriverInfo";
            pst=connection.prepareStatement(sql);
            rs=pst.executeQuery();
            driverinfo_table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        
    }
    private void close_menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_menuitemActionPerformed
        // TODO add your handling code here:
        try {
            setVisible(false);
            LoginPage lp = new LoginPage();
            lp.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                rs.close();
                pst.close();
                connection.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

    }//GEN-LAST:event_close_menuitemActionPerformed

    private void exit_menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_menuitemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit_menuitemActionPerformed

    private void home_toolber_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_toolber_buttonActionPerformed
        // TODO add your handling code here:

        try {
            setVisible(false);
            HomePage hp = new HomePage();
            hp.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                rs.close();
                pst.close();
                connection.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

    }//GEN-LAST:event_home_toolber_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrafficPolicePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrafficPolicePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrafficPolicePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrafficPolicePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrafficPolicePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Date;
    private javax.swing.JMenu Time_menu;
    private javax.swing.JMenu about_menu;
    private javax.swing.JMenuItem close_menuitem;
    private javax.swing.JPanel datatable_tabpane;
    private javax.swing.JTable driverinfo_table;
    private javax.swing.JMenuItem exit_menuitem;
    private javax.swing.JMenu file_menu;
    private javax.swing.JMenu help_menu;
    private javax.swing.JButton home_toolber_button;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_for_tabpane;
    private javax.swing.JPanel report_tabpane;
    private javax.swing.JButton signout_toobar_button;
    private javax.swing.JPanel statistics_tabpane;
    private javax.swing.JTabbedPane tabpane;
    private javax.swing.JToolBar toolber;
    // End of variables declaration//GEN-END:variables
}
